### ISSUE TITLE
Team 11 Review (VnV Plan): Administrator tests unclear inputs

### ISSUE THREAD

**Issue by kierangara** [beatlepie/4G06CapstoneProjectTeam2#107]
@samm82
Name: Team 11 Review
About: Unclear test inputs for administrator tests

### **Summary**
FRT-LE3 to FRT LE6 all contain test inputs that are unclear and would be difficult for a tester to conduct a test based on. LE3 and LE7 both reference "all necessary information" for an event/lecture, but it is unclear what this information would be. A reference to the part of the SRS that dictates what information is required might be one way to make this easier to administer.

FRT-LE4, FRT-LE5, FRT-LE7, FRT-LE8 all mention as an input the "corresponding user request". I believe that refers to the delete/change inputs mentioned in the test procedures below but the input section should be more clear about this.  A specific change to make might also make the tests more concrete for the change tests, as opposed to saying only "update the event/lecture".

### **Deadline**
05/02/2024

### **Estimated Work Hours**
0.5 hours

**Comment by qw33ha** [comment]
Modified the inputs and outputs to be more concrete
