### ISSUE TITLE
Team 11 Review (VnV Plan): NFRT-MS3 ambiguous

### ISSUE THREAD

**Issue by kierangara** [beatlepie/4G06CapstoneProjectTeam2#108]
@samm82
Name: Team 11 Review
About: Ambiguous non-functional requirement test case

### **Summary**
NFRT-MS3 describes the output as "The application works normally" and the result of how the test is performed is stated as the application "runs properly". This does not make it clear what the tester should look for when running this test, or what makes the test successful. What does it mean to "run properly"? There should be some concrete items to look for to determine the success of the test.

### **Deadline**
05/02/2024

### **Estimated Work Hours**
0.5 hours

**Comment by qw33ha** [comment]
Added clear test goals to test the core features' performance
