### ISSUE TITLE
Team 11 Review (VnV Plan): Duplicate Appendix

### ISSUE THREAD

**Issue by SammyG7** [beatlepie/4G06CapstoneProjectTeam2#109]
@samm82 
**Summary**
On page 53 of the document is an appendix heading with a description that indicates that some questions should be answered. The page is blank and this seems to be duplicated on the following page with actual answer. Either remove this heading or fill out the page with new information. 

**Deadline**
05/02/2024

**Estimated Work Hours**
0.25 hours

**Comment by qw33ha** [comment]
Deleted
