### ISSUE TITLE
Team 11 Review (VnV Plan): Missing Requirement IDs

### ISSUE THREAD

**Issue by SammyG7** [beatlepie/4G06CapstoneProjectTeam2#110]
@samm82
**Summary**
There is no traceability between the tests and the new requirements listed in the Hazard Analysis (PR, AVR, RFT). Either add tests if the requirements are missing, or update the ids if they are misaligned. 

**Deadline**
05/02/2024

**Estimated Work Hours**
0.5 hours

**Comment by qw33ha** [comment]
Added a look-up table in SRS since the requirements are renamed
