### ISSUE TITLE
Team 11 Review (VnV Plan): Creation of Unit Testing Plan Before MIS creation

### ISSUE THREAD

**Issue by MatthewCollard** [beatlepie/4G06CapstoneProjectTeam2#111]
@samm82
**Summary**
It is impractical to create a unit testing plan before the decisions on the module have been made in the MIS document. 
Specific unit tests should come after creation of the MIS document.

**Deadline**
05/02/2024

**Estimated Work Hours**
0.5 hours

**Comment by qw33ha** [comment]
Talked to our TA @samm82 and he thinks having some basic ideas of how the unit tests will be implemented will be good at this stage. When the design document is finalized, we'll have a more detailed unit test plan.
