### ISSUE TITLE
Team 11 Review (VnV Plan): HA, UI, FMEA terms not defined

### ISSUE THREAD

**Issue by ethanlucask** [beatlepie/4G06CapstoneProjectTeam2#112]
@samm82
Summary
Several terms are not defined in the Symbols, Abbreviations, and Acronyms, such as HA, UI, and FMEA

![Screenshot_149](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/61300736/d15721d0-ac5f-4d3f-be01-a874d2e59904)

![Screenshot_148](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/61300736/4900e590-16b7-41da-89da-9d5d32a81cec)

Deadline
05/02/2024

Estimated Work Hours
0.25 hours

**Comment by qw33ha** [comment]
Added missing terms
