### ISSUE TITLE
Team 11 Review (VnV Plan): Exact same tests described in different areas

### ISSUE THREAD

**Issue by ethanlucask** [beatlepie/4G06CapstoneProjectTeam2#113]
@samm82 
Summary
Tests  NFRT-MS3 and NFRT-OE2 seem to describe the same exact tests. Please remove one of them.

![Screenshot_151](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/61300736/4bbad623-706d-4d73-b672-591feac83225)

![Screenshot_152](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/61300736/2d87b83c-4ba9-4156-80df-6d543e422a4a)

Deadline
05/02/2024

Estimated Work Hours
0.5 hours

**Comment by qw33ha** [comment]
Resolved in branch docs-VnVPlan-revision-peer-evaluation
