### ISSUE TITLE
Feat: Events Page

### ISSUE THREAD

**Issue by elayanf** [beatlepie/4G06CapstoneProjectTeam2#144]
## Feat Ticket
- **Date**: 2023-12-23
- **Estimated Time to Complete**: <1 week
-  **Assignee**: Firas Elayan
- **Description**: Implement an 'Events' page per the product specifications. It will include the ability to add new events along with their details, view events, and apply the required search filters as specified for the lectures and events pages.

- **Solution**: Your design decisions here (new model, controller and service)

```csharp
public class Sample
{

}
```

- **Image/Video**: Screenshot/video of newly implemented feature, new imported icons

**Comment by qw33ha** [comment]
Close as the feature is implemented in #240 with a new UI
