### ISSUE TITLE
Team 11 Review: Environment variables missing from modules that need them

### ISSUE THREAD

**Issue by ethanlucask** [beatlepie/4G06CapstoneProjectTeam2#181]
@samm82
Name: Team 11 Review

Summary:
Modules such as the Lecture List Manager Module are displaying data to user screen, however, the environment variables are labeled as none.

![Screenshot_269](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/61300736/857296c5-bee7-44df-a67d-f108041c5b59)
![Screenshot_270](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/61300736/0d2d4040-644c-46fe-a5a4-f0ce3c00aa06)

Deadline: Feb 5, 2024

Estimated Work Hours: 20 mins

**Comment by qw33ha** [comment]
Not an issue as we removed the Display method
