### ISSUE TITLE
Team 11 Review: Missing traceability to some requirements

### ISSUE THREAD

**Issue by ethanlucask** [beatlepie/4G06CapstoneProjectTeam2#186]
@samm82
Name: Team 11 Review

Summary:
Some requirements are missing traceability. For requirements that are met by documents, a documentation module should have been created as specified in the avenue announcement.

![Screenshot_272](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/61300736/019622c0-08df-472f-817e-2b617f58d084)

Deadline: Feb 5, 2024

Estimated Work Hours: 20 mins

**Comment by qw33ha** [comment]
Talked with the Ta @samm82, and it seems it is fine to specify a requirement without any traceable modules
