### ISSUE TITLE
Team 11 Review: MG: SQL not defined as a abbreviation 

### ISSUE THREAD

**Issue by MatthewCollard** [beatlepie/4G06CapstoneProjectTeam2#188]
@samm82
Name: Team 11 Review
About: SQL not in the abbreviations section. 

Summary: SQL is used in the appendix of the MG document, but not referenced in the abbreviation section
![image](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/102780755/ab3c2f5b-4899-40af-8f9b-399096b336e6)

Deadline: March 1st

Estimated Work Hours: 0.5 hours

**Comment by millem42** [comment]
SQL is already defined in Section 2.1: Abbreviations and Acronyms

![image](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/98553968/d7bff1ea-b97b-4bad-b29c-5e7a312ac821)
