### ISSUE TITLE
Team 11 Review: MIS: Invalid Assumptions

### ISSUE THREAD

**Issue by kierangara** [beatlepie/4G06CapstoneProjectTeam2#189]
@samm82
Name: Team 11 Review
About: Assumptions about the structure of the program

Summary
Many of the modules include assumptions relating to the structure of the program or types being used in the program. These types and structure related elements should be defined within the module specifications as this information would be needed for an independent programmer to create this program.
![image](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/93633486/9cca493b-964f-4757-b65a-851a447c1796)

Deadline: March 1st

Estimated Work Hours: 1hr

**Comment by qw33ha** [comment]
This assumption is replaced by a similar one from Abstract Object Module
<img width="521" alt="Screen Shot 2024-04-04 at 9 57 02 PM" src="https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/83600619/fa176117-b138-4097-a327-e22cdd3f23ca">
