### ISSUE TITLE
Feat: Lecture Detail View and Edit Lecture Panels

### ISSUE THREAD

**Issue by millem42** [beatlepie/4G06CapstoneProjectTeam2#190]
## Feat Ticket
- **Date**: 2024/01/21
- **Estimated Time to Complete**: 1-2 days
-  **Assignee**: @millem42 
- **Description/Requirements**: The requirement is following:
View Page:
- Show all lecture information
- Edit button to switch to Edit panel
- Back button to close parent canvas
- Pin/Unpin button to pin/unpin lecture
  - Pin: Hide pin icon and show unpin icon, add lecture code under current user
  - Unpin: Vice-versa to pin, remove lecture code under current user
  - Icons should be in the same position
Edit Page:
- Allow user to edit lecture information
- Similar to AddLecPanel
- Save button saves lecture information and goes back to View panel
- Back button to switch to View panel

- **Solution**: 
![image](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/83600619/9fd3c7d6-6b1c-4e34-9b5f-7dc1ef4aecad)
![image](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/83600619/4c85d228-0a1c-496c-9054-39d4afae6edf)
![image](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/83600619/846c7ac9-77e0-49ee-86a6-d63a9a3541ff)

- **Image/Video**: https://www.flaticon.com/free-icon/close_2734822?term=close&page=1&position=1&origin=search&related_id=2734822
https://www.flaticon.com/free-icon/close_2734822?term=close&page=1&position=1&origin=search&related_id=2734822
https://www.flaticon.com/free-icon/thumbtacks_2672102?term=pin&related_id=2672102

**Comment by qw33ha** [comment]
Close the issue, waiting for the branch to be merged
