### ISSUE TITLE
Team 11 Review: No Document Review or reason why Document review was missing

### ISSUE THREAD

**Issue by MatthewCollard** [beatlepie/4G06CapstoneProjectTeam2#266]
@samm82
Name: Team 11 Review
About: No section on Document review in VNV report

Summary: In the VNV plan under non-dynamic testing, there was a section on document review, which was no included or mentioned in the VNV report - Correct me if i'm wrong but unless there is specific detail about this in the weekly meetings, it should be explicitly covered in the VNV report

Deadline: April 1st, 2024

Estimated Work Hours: 2-3 hours

**Comment by qw33ha** [comment]
![image](https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/83600619/93cbfb32-3531-4d78-b050-3f0acaf87d70)
As we said in the document, the weekly meeting/code review and TA feedback are not included, one reason is there are too many of them and they are handled immediately by creating some issues. Please check the repo if you are interested in what's the result of these meetings.
