### ISSUE TITLE
Team 11 Review: NFRT-OE1 does not pass expectations

### ISSUE THREAD

**Issue by MatthewCollard** [beatlepie/4G06CapstoneProjectTeam2#267]
@samm82
Name: Team 11 Review
About: NFRT-OE1 does not pass expectations 

Summary: The Test  NFRT-OE1 does not satisfy the requirement of being downloaded directly from the google play store. I would suggest splitting the test into two separate tests, one for testing just the APK, and one for testing the google play store method.

Deadline: April 1st, 2024

Estimated Work Hours: 1 hr

**Comment by qw33ha** [comment]
The requirement states 'from google play store OR an APK file open to download', so the test still passes. We can remove the google store part from requirement since we are not planning to do it any more.
