### ISSUE TITLE
Team 11 Review: Wording of NFRT-UH2

### ISSUE THREAD

**Issue by ethanlucask** [beatlepie/4G06CapstoneProjectTeam2#269]
@samm82
Name: Team 11 Review
About: Wording of NFRT-UH2

<img width="570" alt="Screenshot 2024-03-08 at 8 07 08 PM" src="https://github.com/beatlepie/4G06CapstoneProjectTeam2/assets/61300736/feadf1a2-a1bc-44df-b2b6-aa72865e45e9">

Summary: The expected/actual output of this test case is not clear. How does convincing the participants that the main features are explained on github solve this requirement? The participants need to make that decision for themselves and let you know what they think, rather than you convincing them, as convincing others is easy if you only show the completed parts and not everything else.

Deadline: April 1st, 2024

Estimated Work Hours: 20 minutes

**Comment by qw33ha** [comment]
There is a word explanation -- user manual in the repo, we just need to let the participants know the existence of that documentation.
