### ISSUE TITLE
FRT-MAP1 Output Ambiguous, Conflicts with NFRT-P2

### ISSUE THREAD

**Issue by SammyG7** [beatlepie/4G06CapstoneProjectTeam2#271]
@samm82
Name: Team 11 Review
About: FRT-MAP1 Output Ambiguous

Summary
FRT-MAP1 specifies user appears on map accurately but provides no threshold for how accurate the data is. The output of NFRT-P2 implies that the tracking isn't as accurate as is desired: "(and sometimes not very accurate)"

Deadline
April 1st, 2024

Estimated Work Hours
30 minutes

**Comment by qw33ha** [comment]
NFRT-P2 checks for the update frequency, not the accuracy. The output of FRT-MAP1 indicates some inaccuracy of user position, but it's still acceptable (around 50m offset) -- and there is no specific requirement about accuracy of GPS any way in SRS
