### ISSUE TITLE
User Module - Unclear Coverage

### ISSUE THREAD

**Issue by SammyG7** [beatlepie/4G06CapstoneProjectTeam2#273]
@samm82
Name: Team 11 Review
About: User Module - Unclear Coverage

Summary
User module has 100% code coverage but doesn't appear to be testing all functionality described in MIS:

- Only appears to have tests for initialization, none of the individual functions
- No branch tests for the index exceptions defined in "Exceptions" section of the MIS table. Do these branches exist or is built in error handling expected to be sufficient 

Note should be added if these are out of scope.

Deadline
April 1st, 2024

Estimated Work Hours
1 hour

**Comment by qw33ha** [comment]
MIS is out of date, the traceability here is between Plan and Report, will update MIS later
