### ISSUE TITLE
Section 10.4 - Change Not Specified

### ISSUE THREAD

**Issue by SammyG7** [beatlepie/4G06CapstoneProjectTeam2#274]
@samm82
Name: Team 11 Review
About: Changes due to load testing unclear

Summary
Section 10.4 specifies that a rough upper bound of 40,000 requests was found and that it serves as a warning for the infrastructure moving forward. It doesn't specify any specifics on how this affected the plan going forward, if at all. Will the upper bound be addressed or left as a soft ceiling for the time being? What was the actual change that came out of this testing?

Deadline
April 1st, 2024

Estimated Work Hours
10 Minutes

**Comment by qw33ha** [comment]
The load testing confirms that the current plan is able to support the number of users(200) for this project. 40,000 is a goal when the project is moved into the next stage (let's say the project is supported by McMaster and becomes an official app). No changes need to be done for this project, this is just a warning for future developers if they decides to move on with this project after Revision 1
