### ISSUE TITLE
Fix: Resolve some feedback from Usability Survey and wrap up some issues

### ISSUE THREAD

**Issue by qw33ha** [beatlepie/4G06CapstoneProjectTeam2#277]
## Bug Ticket
- **Date**: 2024/03/10
- **Estimated Time to Complete**: 2-3 days
-  **Assignee**:
- **Description/Requirements**: The requirement is following:
- [x] Rename: Pin/Unpin -> Save/Unsave
    - @beatlepie  
- [x] Saved items are hidden in profile -> A button from List to User Profile, also a button from Saved to list (which mean if we add some filter here, we can save the effort to build detail view, or we can add detail view, in that case a button from saved to all is not necessary)
    - @beatlepie  
- [x] Apply Pagination class to the scenes
    - @qw33ha 
- [x] DB & Auth refactoring
    - @beatlepie  
- [x] Email verification & delete account update
    - @beatlepie 
- [x] Advanced chatting: Link to lecture and event
    - @qw33ha 
- [x] Chatting polishing: Add nickname to the top bar, apply text bubbles 
    - @Haxerus  

- **Image/Video**: Screenshot/video of newly implemented feature, new imported icons

**Comment by beatlepie** [comment]
Changing pinned to bookmark instead, as suggested alternative

**Comment by beatlepie** [comment]
The images are not correct, but the images for list -> bookmarks can easily be changed
