### ISSUE TITLE
TA Feedback (VnV Report)

### ISSUE THREAD

**Issue by millem42** [beatlepie/4G06CapstoneProjectTeam2#301]
### Summary
The following issues should be resolved:

#### LO_Synthesize: Synthesizes the results of an investigation to reach valid conclusions
Mark: 2.5/3
- [x] It seemed like the survey could have used some more questions, and some more investigation into Requests vs. Response Time would be nice.
    - Added more questions in VnV Plan for the survey
    - Added investigation into load test limitations. @Haxerus 

#### Content
Mark: 2/3
- [x] "Unsuccessful Account Creation" is a vague name for this test, since there are potentially many ways an account creation could be unsuccessful. It looks like there is a bug in FRT-UA9: "newProgram: Computer Science" exists both in the initial state and the test input.
    - Done, add more details to the name of the test, fix UA9 typo, the newProgram in the input is removed
- [x] "Semail" and "Temail" should be listed in your table of symbols, etc.; even though it is defined in FRT-SN2-3, this information should at a bare minimum be in this table and in its first usage in the document. What does it mean for "A Request [to be] sent to the target user" in FRT-SN1? How is this checked? Do any of FRT-SN2-5 send any notifications to the users involved?
    - Added new terms to the table of symbols, added more explanation to SN1 output (the request is added to the target request list), and currently there is no sound effect or any notifications. Once a request is accepted, the friend will be added automatically to their friend list, and once a request is rejected, nothing happens (that is a design on purpose). Although users can see if their friend request list is empty (if not there will be a red badge), we do not have something like sound effect notifications for the friend request system.
- [x] In FRT-LE5-6 and 8-9, what if a lecture/event with a given name already exists? Are recurring lectures handled, or out of scope? What if a nonexistent lecture/event is attempted to be deleted in FRT-LE7/10?
    - Added new test for adding a lecture with a name that's been used in the system. Recurring lectures are handled just like all other lectures. To handle recurring lectures, the time of a lecture is set to be a string instead of a number or a time format so that the creator can specify whatever time.
- [x] FRT-LE13-14 have insufficient initial states to accurately test what they should! Some ambiguity; e.g., "periodically".
    - Added more details to the initial states, change periodically to every semester (that ambiguity comes from the requirement, the actual test result says 'every semester')
 
#### Spelling and grammar and style
Mark: 2.5/3
- [x] Minor grammar issues; typo in "isPulbic"
- [x] A nitpick: I would get rid of the lines between entries in your table of symbols, etc., and longer entries (like NUnit) should wrap around so the table isn't too wide (no penalty for this, though).

#### VnV Report Matches VnV Plan
Mark: 3/3
- [x] MIN_SCORE is not defined and its location is not referenced; assuming it is in the SRS, I found it to be 7/10, which is confusing when your criteria are given on a 1-5 scale, making it not readily apparent if they these tests have passed or not.
    - All symbols are defined in VnV Plan as we mentioned in the document, and the min score is 3.5 in the plan

#### Nonfunctional quality 1
Mark: 2.5/3
**Usability**
- [x] NFRT-UH2 doesn't seem like a clear test - how are you sure you've "convinced the participants that the main features are explained in the GitHub repo"? If "the main features are explained in the GitHub repo", then the test should be if they can locate it, have access to it, and understand the features based on what is in the repo! Other tests have a similar issue.
    - Reworded some nonfunctional tests

#### Nonfunctional quality 2
Mark: 1.5/3
**Security**
- [x] Many "performance requirements" are actually security requirements, such as NFRT-P3-4/7-8.
    - Changed all corresponding parts in HA, SRS VnV Report and Plan
- [x] The requirements about valid characters in usernames/passwords are unclear: "special characters" are forbidden in NFRT-P7, but I would have thought "-", which appears in some of your test cases, is a special character. Your test case for NFRT-P8 has the potential to overlap with NFRT-P7, implying it's not really an atomic test.
    - Add special characters to the table of symbols. user input (just nickname actually) and email have two different validation processes, some special characters are allowed in email but not in the nickname and vice versa. Therefore we decide to separate them into two tests.
- [x] As mentioned above, "convinc[ing] the participants" of something is a weak test criteria; how could these be tested more practically?
- [x] Extra credit: how would you avoid a [user enumeration vulnerability](https://www.rapid7.com/blog/post/2017/06/15/about-user-enumeration/)?
    - Added an extra section under changes due to testing about enumeration attack

#### Changes made in response to VnV
Mark: 3/3
No issues

#### Issues Created for Another Team
Mark: 2/3
- [x] For # 233, there isn't a relevant section in the VnVReport template, which makes me think that this is out of scope of this deliverable. Disregarding duplicates and minor issues, there are five high quality issues here, although try to include as much helpful information as possible!

### Deadline
April 4, 2024

### Estimated Work Hours
3 Hours

**Comment by beatlepie** [comment]
Only removed lines form table of symbols, as it is nitpick and no marks were removed
