### ISSUE TITLE
Team11 Review: SRS Acronym Usage

### ISSUE THREAD

**Issue by ethanlucask** [beatlepie/4G06CapstoneProjectTeam2#65]
---
@samm82
name: Team11 Review
about: Terms/Acronyms not defined before usage
---

## Summary
- Section 2.3 of the SRS uses the term AR and UI/UX, however, these acronyms are not defined previously.

## Deadline
- 23/10/2023

## Estimated Work Hours
- 15 mins

**Comment by elayanf** [comment]
Acronyms added to the terminology section
