### ISSUE TITLE
Team11 Review: Non-Functional Requirements Fit Criterion

### ISSUE THREAD

**Issue by ethanlucask** [beatlepie/4G06CapstoneProjectTeam2#66]
---
@samm82 
name: Team 11 Review
about: Many Non-Functional Requirements are ambiguous. Good idea to add Fit Criterion

---

## Summary
-  Many Non-Functional Requirements are ambiguous so it will be tough to know if they have been met. For example, one NFR for Personalization and Internationalization Requirements states: "The product shall provide information about ongoing lectures and events personalized to each user". What kind of information will be provided? (ie. Lecture times?, Lecture locations?, etc.) Adding fit criterion may help resolve this.

## Deadline
- 23/10/2023

## Estimated Work Hours
- 1 hr

**Comment by elayanf** [comment]
Fit criteria added to the NFRs
