### ISSUE TITLE
Team11 Review: Missing citations for external information

### ISSUE THREAD

**Issue by kierangara** [beatlepie/4G06CapstoneProjectTeam2#69]
@samm82
name: Team 11 Review
about: Missing citations for external information

### **Summary**
In section "5.1 Relevant Facts" a reference is made to the McMaster University regulations preventing collection of schedules. There is no citation anywhere in the document providing the location of these regulations. This should be added to allow the reader to see the source of this constraint, and view any other potential constraints. 

### **Deadline**
05/02/2024

### **Estimated Work Hours**
0.5 hrs

**Comment by elayanf** [comment]
References added to parts that cite external content.
