### ISSUE TITLE
Lack of Solution/ Implementation Environment Constraints 

### ISSUE THREAD

**Issue by SammyG7** [beatlepie/4G06CapstoneProjectTeam2#72]
There is a conflict between the mandated constraints and the mission statement set out by the rest of the document. Mainly, the implementation environment constraints (Section 3.2) describes the fact that there are no constraints on the environment that the product will be created for, despite multiple references throughout the document about the final product being a mobile application. At a minimum this section should talk about the constraints of being built for phones, which is a much more restrictive environment than PCs.

**Comment by qw33ha** [comment]
Added constraints mentioning the application must support Android 11 and above
