### ISSUE TITLE
Team11 Review: Missing unique identifiers for requirements

### ISSUE THREAD

**Issue by kierangara** [beatlepie/4G06CapstoneProjectTeam2#73]
@samm82
name: Team 11 Review
about: Missing unique identifiers for requirements

### **Summary**
The functional requirements have numbering but aren't specifically provided tags for each requirement, while individual non-functional requirements are missing identifiers all together and are only defined by their section. Per the "Document Organization" section of the SRS rubric, all requirements should have a unique identifier. This will make it easier to reference individual requirements both in other sections of this document, as well as in future related documents and in design discussions.

### **Deadline**
05/02/2024

### **Estimated Work Hours**
0.5 hrs

**Comment by elayanf** [comment]
FRs and NFRs all given unique identifiers.
