### ISSUE TITLE
Standardize NFR Format

### ISSUE THREAD

**Issue by SammyG7** [beatlepie/4G06CapstoneProjectTeam2#74]
The format for listing nonfunctional requirements jumps between point form (Sections 10-13, 16, 18-19) and paragraph form (Sections 14, 15, 17). Changing these to one uniform format will make it easier to read. 

This can also be used as an opportunity to label the NFRs will acronyms and numbers (Ex. LF1) for easier reference.

**Comment by elayanf** [comment]
All NFRs standardized to point form.
